### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by ProgSys** [Sandern/lambdawars#3]
I was hosting a lobby when the game of another player crashed.
It could be something to do with the sound system, as there was a strage sound reported.
Sadly there is not much else.

Dump:
[lambdawars_4993_crash_2017_2_19T22_41_12C0.zip](https://github.com/Sandern/lambdawars/files/786317/lambdawars_4993_crash_2017_2_19T22_41_12C0.zip)

**Comment by Sandern** [comment]
Couldn't find much in the crash dump, so closing issue.
