### ISSUE TITLE
Chromium Embedded Framework's implementation on other source base mod

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [Sandern/lambdawars#4]
Hello, I know that I do not count as a problem but I have loved its mod and the gameplay absolutely all aspects of it. But I have curious how it is that they implemented the "Chromium Embedded Framework", because I have not found how to implement it In my mod I would be very grateful and will give credits to you :D

**Comment by Sandern** [comment]
What parts do you want to know? You can find most of the implementation in https://github.com/Sandern/lambdawars/tree/develop/src/game/client/cef and https://github.com/Sandern/lambdawars/tree/develop/src/cef_process_helper.

**Comment by FriskTheFallenHuman** [comment]
Oh many thanks: D hey but I have a doubt already add all the files related to my mod but I do not know how to make the Mod use the CEF as menu is that I was used to using the method that used TF2 to overwrite the Menu

**Comment by Sandern** [comment]
Alien Swarm SDK has the game ui embedded in the game and allows you to modify it whatever way you want. However Source SDK 2013 still has it as a separate project not part of the SDK, so you are more limited in the modifications you can make.

**Comment by FriskTheFallenHuman** [comment]
I think it is possible to import the GameUI from the Swarm Alien to Source 2013 but for that you would have to use the Code Leak of the Source 2007 but that would be impossible or use the GameUI2 that is a port of that method to the new SDK is something What was I thinking

**Comment by FriskTheFallenHuman** [comment]
What I could find was that if you can because the interfaces needed for it are IGameUI and IGameConsole (which is to modify or use when the console is open exists and you can access it but the code of that file is in the wiki Of Valve)
